---
# tasks file for ansible-role-node_exporter_prometheus
- name: Download node_exporter version
  get_url:
     url: "{{ node_exporter_download_url }}"
     dest: "{{ node_exporter_download_location }}/{{node_exporter_downlaod_file}}.tar.gz"

- name: untar node_exporter
  unarchive:
     remote_src: yes
     src: "{{ node_exporter_download_location }}/{{node_exporter_downlaod_file}}.tar.gz"
     dest: "{{ node_exporter_download_location }}"

- name: create /var/lib/node_exporter directory
  file:
    path: /var/lib/node_exporter
    state: directory

- name: copy node_exporter to /var/lib/node_exporter directory
  command: cp -rpf {{ node_exporter_download_location }}/{{node_exporter_downlaod_file}}/node_exporter /var/lib/node_exporter/

- name: create node_exporter service in systemd for CentOS
  template:
    src: node_exporter.service.j2
    dest: /usr/lib/systemd/system/node_exporter.service
    owner: root
    group: root
  when: ansible_distribution == "CentOS"

- name: create node_exporter service in systemd for Ubuntu
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
  when: ansible_distribution == "Ubuntu"

- name: start node_exporter service
  systemd:
     name: node_exporter
     state: started
  register: node_exporter_start

- debug:
    msg: "{{ node_exporter_start }}"
